#!/usr/bin/env python
#
# Compares a matrix saved from Python with one generated by C++
#

import ast
import sys

import numpy as np

if len(sys.argv) != 3:
    print("Usage: compare_matrix.py <matrix file from python> <matrix file from C++>")
    sys.exit(1)

# load the Python matrix from pickle file
pymat = np.load(sys.argv[1])

# load the C++ matrix from text file
f = open(sys.argv[2], 'r')
file_contents = f.read()
f.close()
l = ast.literal_eval(file_contents)
cppmat = np.array(l)

# check size matches
if pymat.shape != cppmat.shape:
    print("Shape mismatch!", pymat.shape, cppmat.shape)
    sys.exit(1)

# check contents match
if np.allclose(pymat, cppmat):
    print("Matrices match within tolerance")
    sys.exit(0)
else:
    print("Matrices do NOT match!")
    sys.exit(1)

